# Site
name: "Marcos Bacon"
title: "Marcos Bacon"
description: "Sound Design, educação musical e outras nerdices."
logo: 'assets/images/marcosbacon-2021.png'
favicon: 'assets/images/favicon-beico.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: kakobacon@gmail.com

# Authors
authors:
  sal:
    name: Marcos Bacon
    display_name: bacon
    gravatar: d99e6e8adbf2167e0ad4176ea794b0d3
    email: kakobacon@gmail.com
    web: https://instagram.com/marcos.bacon
    twitter: https://twitter.com/marcos.bacon
    description: "It's not worth describing me."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3936501232619162"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Setting default front matter
#defaults:
#  -
#  scope:
#    path: "" # an empty string here means all files in the project
#  values:
#    image: "/assets/images/favicon-beico.png"
